services:
  tor:
    image: dperson/torproxy
    container_name: tor-proxy
    restart: always
    ports:
      - "9050:9050"
    networks:
      - devnetwork

  server:
    image: vovanvh/voca:stats-dev
    container_name: krys-stats
    build: docker/python/dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    env_file:
      - .env
    environment:
      - TOR_PROXY_HOST=tor-proxy
      - TOR_PROXY_PORT=9050
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - tor
    networks:
      - devnetwork
networks:
  devnetwork:
    external: true
